In [2]:
import numpy as np 

In [3]:
#der Skalar/Skalare = Tensor 0. Ordnung
S = 5
S_array = np.array(S)
type(S_array), S_array.shape, S_array.dtype
#punkt hat keine Dimension, deshalb shape = ()

(numpy.ndarray, (), dtype('int32'))

In [4]:
#der Vektor/Vektoren = Tensor 1. Ordnung
V = np.array([1, 2, 3, 4, 5])
type(V), V.shape, V.dtype

(numpy.ndarray, (5,), dtype('int32'))

In [5]:
V_col = V.reshape(5,1) #Vektor in Spaltenvektor umwandeln
V_row = V.reshape(1,5) #Vektor in Zeilenvektor umwandeln
V_col, V_row

(array([[1],
        [2],
        [3],
        [4],
        [5]]),
 array([[1, 2, 3, 4, 5]]))

In [6]:
#die Matrix/Matritzen  = Tensor 2. Ordnung
M = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
type(M), M.shape, M.dtype

(numpy.ndarray, (3, 3), dtype('int32'))

In [7]:
#der Tensor 3. Ordnung = eine Sammlung von Matritzen
M2 = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]])
T = np.array([M, M2])
print(T)
type(T), T.shape, T.dtype

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


(numpy.ndarray, (2, 3, 3), dtype('int32'))

In [10]:
#matrix addition
M3 = M + M2
M4 = M + 5
M5 = M - M2
M6 = M - 5
#M4 und M6 sind Broadcasting

In [ ]:
#Vektor transponieren
#eindimensionale Arrays können nicht transponiert werden, aber ein umgeformter Vektor kann
V.T.shape, V_col.T.shape

((5,), (1, 5))

In [11]:
#Matrix transponieren
M.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [20]:
#Matrix multiplizieren
#skalarpodukt = inneres Produkt = Punktpodukt (dot product)
np.dot(V, V), np.dot(V, V.T)

(55, 55)

In [24]:
#Matrix multiplizieren
#m1 (m x n) * m2 (n x p) = m3 (m x p)
M7 = np.array([[1, 2], [3, 4], [5, 6]])
M8 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
np.dot(M7, M8)

array([[11, 14, 17, 20],
       [23, 30, 37, 44],
       [35, 46, 57, 68]])